/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  RX_PROJECT_Y_2_0                       */
/*      FILE         :  sbrk.h                                 */
/*      DESCRIPTION  :  Header file of sbrk file               */
/*      CPU SERIES   :  RX200                                  */
/*      CPU TYPE     :  RX23T                                  */
/*                                                             */
/*      This file is generated by e2 studio.                   */
/*                                                             */
/***************************************************************/

/* size of area managed by sbrk */
#define HEAPSIZE 0x400